image: docker:latest

docker:branch:
  stage: deploy
  script:
    - docker build -t $CI_BUILD_REF .
    - docker tag $CI_BUILD_REF $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  tags:
    - 2immerse
    - docker
  only:
    - branches
  except:
    - master

docker:latest:
  stage: deploy
  script:
    - docker build -t $CI_BUILD_REF .
    - docker tag $CI_BUILD_REF $CI_REGISTRY_IMAGE:latest
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - 2immerse
    - docker
  only:
    - master

docker:tag:
  stage: deploy
  script:
    - docker build -t $CI_BUILD_REF .
    - docker tag $CI_BUILD_REF $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  tags:
    - 2immerse
    - docker
  only:
    - tags
